---
- name: Gather Facts using Credentials Set 1
  hosts: ssh
  gather_facts: false

  vars:
    ansible_user: "{{ ansible_user_1 }}"
    ansible_password: "{{ ansible_pass_1 }}"

  tasks:
    - name: Block Handle issues
      block:
        - name: Quick SSH Discovery Test
          ansible.builtin.command: >
            timeout 15s sshpass -p '{{ ansible_password }}'
            ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no
            -o PreferredAuthentications=password -o PubkeyAuthentication=no
            {{ ansible_user }}@{{ inventory_hostname }} "cat /etc/os-release"
          delegate_to: localhost
          register: ssh_output
          no_log: true

        - name: Set Fact
          ansible.builtin.set_fact:
            ssh_connection: true
          when: ssh_output.rc == 0

        - name: Create 'unreachable_hosts' group
          ansible.builtin.add_host:
            name: "{{ item }}"
            groups: unreachable_hosts
          loop: "{{ ansible_play_hosts_all }}"
          when: hostvars[item]['ssh_connection'] | default(false) == false

        - name: Run Setup to gather facts
          ansible.builtin.setup:
            gather_timeout: 60
          timeout: 60

        - name: Update SNOW CMDB
          servicenow.itsm.configuration_item:
            state: present
            name: "{{ ansible_fqdn }}"
            ip_address: "{{ ansible_default_ipv4.address | default(omit) }}"
            sys_class_name: cmdb_ci_linux_server
            other:
              fqdn: "{{ ansible_fqdn | default(omit) }}"
              os: "{{ ansible_distribution + ansible_distribution_major_version | default(omit) }}"
              host_name: "{{ ansible_fqdn | default(omit) }}"
              cpu_count: "{{ ansible_processor_vcpus }}"
          delegate_to: localhost

      rescue:

        - name: Clear errors so the next play can see these hosts
          ansible.builtin.meta: clear_host_errors

        - name: End play
          ansible.builtin.meta: end_play

- name: Gather Facts using Credentials Set 2
  hosts: unreachable_hosts
  gather_facts: false

  vars:
    ansible_user: "{{ ansible_user_2 }}"
    ansible_password: "{{ ansible_pass_2 }}"

  tasks:
    - name: Block Handle issues
      block:
        - name: Run Setup to gather facts
          ansible.builtin.setup:
            gather_timeout: 60
          timeout: 60

        - name: Update SNOW CMDB
          servicenow.itsm.configuration_item:
            state: present
            name: "{{ ansible_fqdn }}"
            ip_address: "{{ ansible_default_ipv4.address | default(omit) }}"
            sys_class_name: cmdb_ci_linux_server
            other:
              fqdn: "{{ ansible_fqdn | default(omit) }}"
              os: "{{ ansible_distribution + ansible_distribution_major_version | default(omit) }}"
              host_name: "{{ ansible_fqdn | default(omit) }}"
              cpu_count: "{{ ansible_processor_vcpus }}"
          delegate_to: localhost

      rescue:
        - name: Create 'unreachable_hosts_2' group
          ansible.builtin.add_host:
            name: "{{ item }}"
            groups: unreachable_hosts_2
          loop: "{{ ansible_play_hosts_all | difference(ansible_play_batch) }}"
          run_once: true

        - name: Clear errors so the next play can see these hosts
          ansible.builtin.meta: clear_host_errors

        - name: End play
          ansible.builtin.meta: end_play


- name: Gather Facts on remaining hosts using Windows Credentials
  hosts: unreachable_hosts_2
  gather_facts: false

  vars:
    ansible_user: "{{ ansible_user_3 }}"
    ansible_password: "{{ ansible_pass_3 }}"

  tasks:
    - name: Block Handle issues
      block:
        - name: Run Setup to gather facts
          ansible.builtin.setup:
            gather_timeout: 60
          timeout: 60
          vars:
            ansible_shell_type: powershell

        - name: Update SNOW CMDB
          servicenow.itsm.configuration_item:
            state: present
            name: "{{ ansible_fqdn }}"
            ip_address: "{{ ansible_interfaces[0].ipv4.address | default(omit) }}"
            sys_class_name: cmdb_ci_win_server
            other:
              fqdn: "{{ ansible_fqdn | default(omit) }}"
              os: "{{ ansible_distribution | default(omit) }}"
              host_name: "{{ ansible_fqdn | default(omit) }}"
              cpu_count: "{{ ansible_processor_vcpus }}"
          delegate_to: localhost

      always:
        - name: Get final list of unreachable hosts
          ansible.builtin.add_host:
            name: "{{ item }}"
            groups: unreachable_hosts_final
          loop: "{{ ansible_play_hosts_all | difference(ansible_play_batch) }}"
          run_once: true

        - name: Clear errors so the next play can see these hosts
          ansible.builtin.meta: clear_host_errors

        - name: End play
          ansible.builtin.meta: end_play

- name: Show Hosts Report
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Consolidate Host version data into a report"
      ansible.builtin.set_fact:
        host_report: |
          {%- set summary = {} -%}
          {%- for host in groups['ssh'] | difference(groups['unreachable_hosts_final']) -%}
            {%- set ver = hostvars[host].ansible_facts['distribution'] | default('Unknown') -%}
            {%- if ver not in summary -%}
              {%- set _ = summary.update({ver: []}) -%}
            {%- endif -%}
            {%- set _ = summary[ver].append(host) -%}
          {%- endfor -%}

          REPORT: HOST DISTRIBUTION
          =================================
          {% for version in summary.keys() | sort %}
          Version: {{ version }}
          {% for host in summary[version] | sort %}
          - {{ host }}
          {% endfor %}

          {% endfor %}
          {%- set unreachable = groups['unreachable_hosts_final'] -%}
          {%- if unreachable %}
          UNREACHABLE HOSTS
          =================
          {% for host in unreachable | sort %}
          - {{ host }}
          {% endfor %}
          {%- endif %}

    - name: "Emit formatted report to console"
      ansible.builtin.debug:
        msg: "{{ host_report.split('\n') }}"
