---
- name: Gather Facts using Credentials Set 1
  hosts: ssh
  gather_facts: false

  vars:
    ansible_user: "{{ ansible_user_1 }}"
    ansible_password: "{{ ansible_pass_1 }}"

  tasks:
    - name: Quick SSH Discovery Test
      ansible.builtin.command: >
        timeout 15s sshpass -p '{{ ansible_password }}'
        ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no
        -o PreferredAuthentications=password -o PubkeyAuthentication=no
        {{ ansible_user }}@{{ inventory_hostname }} "cat /etc/os-release"
      delegate_to: localhost
      register: ssh_output
      no_log: true

    - name: Set Fact
      ansible.builtin.set_fact:
        ssh_connection: true
      when: ssh_output.rc == 0

    - name: Create 'unreachable_hosts' group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: unreachable_hosts
      loop: "{{ ansible_play_hosts_all }}"
      when: hostvars[item]['ssh_connection'] | default(false) == false

    - name: Get Hostname
      ansible.builtin.raw: cat /proc/sys/kernel/hostname
      register: hostname
      changed_when: hostname.rc > 0
      timeout: 30

    - name: Get OS
      ansible.builtin.raw: cat /etc/redhat-release
      register: os
      changed_when: os.rc > 0
      timeout: 30

    - name: Get IP
      ansible.builtin.raw: ip -4 -o addr show scope global | awk '{split($4,a,"/"); print a[1]}' | grep -v '[#]' | head -2 | tail -1
      register: ip_address
      changed_when: ip_address.rc > 0
      timeout: 30

    - name: Get cores
      ansible.builtin.raw: cat /proc/cpuinfo 2>/dev/null | grep '^processor\s*.' | wc -l
      register: cores
      changed_when: cores.rc > 0
      timeout: 30

    - name: Update SNOW CMDB
      servicenow.itsm.configuration_item:
        state: present
        name: "{{ hostname.stdout }}"
        ip_address: "{{ ip_address.stdout | default(omit) }}"
        sys_class_name: cmdb_ci_linux_server
        other:
          fqdn: "{{ hostname.stdout | default(omit) }}"
          os_domain: "{{ os.stdout | default(omit) }}"
          host_name: "{{ hostname.stdout | default(omit) }}"
          cpu_count: "{{ cores.stdout | default(omit) }}"
      delegate_to: localhost

    - name: Clear errors so the next play can see these hosts
      ansible.builtin.meta: clear_host_errors

    - name: End play
      ansible.builtin.meta: end_play

- name: Gather Facts using Credentials Set 2
  hosts: unreachable_hosts
  gather_facts: false

  vars:
    ansible_user: "{{ ansible_user_2 }}"
    ansible_password: "{{ ansible_pass_2 }}"

  tasks:
    - name: Get Hostname
      ansible.builtin.raw: cat /proc/sys/kernel/hostname
      register: hostname
      changed_when: hostname.rc > 0
      timeout: 30

    - name: Get OS
      ansible.builtin.raw: cat /etc/redhat-release
      register: os
      changed_when: os.rc > 0
      timeout: 30

    - name: Get IP
      ansible.builtin.raw: ip -4 -o addr show scope global | awk '{split($4,a,"/"); print a[1]}' | grep -v '[#]' | head -2 | tail -1
      register: ip_address
      changed_when: ip_address.rc > 0
      timeout: 30

    - name: Get cores
      ansible.builtin.raw: cat /proc/cpuinfo 2>/dev/null | grep '^processor\s*.' | wc -l
      register: cores
      changed_when: cores.rc > 0
      timeout: 30

    - name: Update SNOW CMDB
      servicenow.itsm.configuration_item:
        state: present
        name: "{{ hostname.stdout }}"
        ip_address: "{{ ip_address.stdout | default(omit) }}"
        sys_class_name: cmdb_ci_linux_server
        other:
          fqdn: "{{ hostname.stdout | default(omit) }}"
          os_domain: "{{ os.stdout | default(omit) }}"
          host_name: "{{ hostname.stdout | default(omit) }}"
          cpu_count: "{{ cores.stdout | default(omit) }}"
      delegate_to: localhost

    - name: Set Fact
      ansible.builtin.set_fact:
        ssh_connection: true
      when: hostname.rc == 0

    - name: Create 'unreachable_host_2' group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: unreachable_hosts_2
      loop: "{{ ansible_play_hosts_all }}"
      when: hostvars[item]['ssh_connection'] | default(false) == false

    - name: Clear errors so the next play can see these hosts
      ansible.builtin.meta: clear_host_errors

    - name: End play
      ansible.builtin.meta: end_play

- name: Gather Facts on remaining hosts using Windows Credentials
  hosts: unreachable_hosts_2
  gather_facts: false

  vars:
    ansible_user: "{{ ansible_user_3 }}"
    ansible_password: "{{ ansible_pass_3 }}"

  tasks:
    - name: Get Hostname
      ansible.builtin.raw: '[System.Net.Dns]::GetHostEntry($env:computername).HostName'
      register: hostname
      changed_when: hostname.rc > 0
      timeout: 30

    - name: Get OS
      ansible.builtin.raw: (Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion').ProductName
      register: os
      changed_when: os.rc > 0
      timeout: 30

    - name: Get IP
      ansible.builtin.raw: Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -NotLike '*Loopback*'} | Select-Object -ExpandProperty IPAddress
      register: ip_address
      changed_when: ip_address.rc > 0
      timeout: 30

    - name: Get cores
      ansible.builtin.raw: (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
      register: cores
      changed_when: cores.rc > 0
      timeout: 30

    - name: Update SNOW CMDB
      servicenow.itsm.configuration_item:
        state: present
        name: "{{ hostname.stdout }}"
        ip_address: "{{ ip_address.stdout | default(omit) }}"
        sys_class_name: cmdb_ci_linux_server
        other:
          fqdn: "{{ hostname.stdout | default(omit) }}"
          os_domain: "{{ os.stdout | default(omit) }}"
          host_name: "{{ hostname.stdout | default(omit) }}"
          cpu_count: "{{ cores.stdout | default(omit) }}"
      delegate_to: localhost

    - name: Set Fact
      ansible.builtin.set_fact:
        ssh_connection: true
      when: hostname.rc == 0

    - name: Create 'unreachable_hosts_final' group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: unreachable_hosts_final
      loop: "{{ ansible_play_hosts_all }}"
      when: hostvars[item]['ssh_connection'] | default(false) == false

    - name: Clear errors so the next play can see these hosts
      ansible.builtin.meta: clear_host_errors

    - name: End play
      ansible.builtin.meta: end_play

- name: Show Hosts Report
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "Consolidate Host version data into a report"
      ansible.builtin.set_fact:
        host_report: |
          {%- set unreachable = groups['unreachable_hosts_final'] -%}
          {%- if unreachable %}
          UNREACHABLE HOSTS
          =================
          {% for host in unreachable | sort %}
          - {{ host }}
          {% endfor %}
          {%- endif %}

    - name: "Emit formatted report to console"
      ansible.builtin.debug:
        msg: "{{ host_report.split('\n') }}"
