---
- name: Patch Servers
  hosts: all

  tasks:
    - name: Block for Patching
      block:
        - name: Pre-check role
          ansible.builtin.include_role:
            name: shadowman_pre_checks

        - name: Patching role
          ansible.builtin.include_role:
            name: shadowman_patching

        - name: Post-check role
          ansible.builtin.include_role:
            name: shadowman_post_checks

      rescue:
        - name: Snapshot restore on failure
          ansible.builtin.include_role:
            name: shadowman_snapshot_restore

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_patch
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
