---
- name: Patch Servers based on environment and owner
  hosts: tag_{{ env }}:&tag_{{ owner.split('@')[0] }}*

  roles:
    - shadowman_patching

  tasks:

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_patch
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
