---
- name: Install Windows Package
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Windows Package
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packagename }}"
        state: "{{ packagestate }}"