---
- name: Windows patching playbook
  hosts: all
  gather_facts: false

  collections:
    - ansible.windows
    
  tasks:

  - name: Check for packages to include
    ansible.builtin.set_fact:
      accept_packages: "{{ acceptlist.split(',') }}"
    when: acceptlist != ''

  - name: Check for packages to exclude
    ansible.builtin.set_fact:
      reject_packages: "{{ rejectlist.split(',') }}"
    when: rejectlist != ''

  - name: Install Windows Updates
    ansible.windows.win_updates:
      category_names: "{{ categories | default(omit) }}"
      reboot: '{{ reboot_server | default(yes) }}'
      accept_list: "{{ accept_packages | default(omit) }}"
      reject_list: "{{ reject_packages | default(omit) }}"
    register: patchresult

  - name: Display Patching Results
    ansible.builtin.debug:
      msg: "{{ patchresult | json_query('updates[*].title') }}"