---
- name: Windows patching playbook
  hosts: all

  roles:
    - shadowman_patching

  tasks:

    - name: Build the report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_windows_patch
        apply:
          delegate_to: report.shadowman.dev
          run_once: true