---
- name: Pull AAP Metrics
  community.postgresql.postgresql_query:
    db: awx
    query: SELECT * FROM public.main_hostmetric WHERE last_automation >= '{{ ansible_date_time.year }}-{{ ansible_date_time.month }}-01 00:00:00' AND last_automation <= '{{ ansible_date_time.year }}-{{ ansible_date_time.month }}-{{ ansible_date_time.day }} {{ ansible_date_time.time }}' ORDER BY last_automation DESC
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
  register: aapmetrics

- name: Host Automated
  ansible.builtin.debug:
    msg: "{{ aapmetrics.rowcount }}"

- name: Display Host Automated Information
  ansible.builtin.debug:
    msg: "{{ aapmetrics.query_result }}"
