---
- name: Add Windows host to AD
  microsoft.ad.membership:
    dns_domain_name: ad.shadowman.dev
    hostname: "{{ fqdn.split('.')[0] }}"
    domain_admin_user: "{{ domainuser }}"
    domain_admin_password: "{{ domainpassword }}"
    state: domain
    reboot: true

- name: Ensure DNS record is created for Windows on OCPV
  community.general.ipa_dnsrecord:
    name: "{{ fqdn.split('.shadowman.dev')[0] }}"
    state: present
    zone_name: "shadowman.dev"
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    record_type: "A"
    record_value: "{{ ip_addr }}"
  delegate_to: localhost
  when: shadowman_provision_hypervisor|default('RHV') == "OCPV"
