---
- name: Install Insights and OpenSCAP
  ansible.builtin.dnf:
    name:
      - openscap-scanner
      - scap-security-guide
      - insights-client
    state: present

- name: Ensure Satellite Parameter is set to allow Insights
  redhat.satellite.host:
    name: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    parameters:
      - name: "host_registration_insights"
        parameter_type: "boolean"
        value: "true"
      - name: "host_registration_remote_execution"
        parameter_type: "boolean"
        value: "true"
      - name: "host_registration_remote_execution_pull"
        parameter_type: "boolean"
        value: "false"
      - name: "host_update_packages"
        parameter_type: "boolean"
        value: "false"
  when: shadowman_provision_hypervisor|default('RHV') == "VMWare"

- name: Register Insights Client
  redhat.insights.insights_register:
    state: present
