---
- name: Snapshot Restore VMWare
  ansible.builtin.include_tasks: shadowman_vmware_snapshot_restore.yml
  when: shadowman_provision_hypervisor == "VMWare"

- name: Snapshot Restore Azure
  ansible.builtin.include_tasks: shadowman_azure_snapshot_restore.yml
  when: shadowman_provision_hypervisor == "Azure"

- name: Snapshot Restore AWS
  ansible.builtin.include_tasks: shadowman_aws_snapshot_restore.yml
  when: shadowman_provision_hypervisor == "AWS"

- name: Snapshot Restore OpenShift Virtualization
  ansible.builtin.include_tasks: shadowman_openshift_snapshot_restore.yml
  when: shadowman_provision_hypervisor == "OCPV"
