---
- name: Get VM info
  vmware.vmware.guest_info:
    name: "{{ inventory_hostname }}"
    datacenter: "Shadowman-DC"
    validate_certs: false
  register: vm_info
  delegate_to: localhost

- name: Turn off VM
  vmware.vmware.vm_powerstate:
    moid: "{{ vm_info.guests[0].moid }}"
    datacenter: "Shadowman-DC"
    state: powered-off
    validate_certs: false
  delegate_to: localhost

- name: Revert to Snapshot for VMWare
  vmware.vmware.vm_snapshot_revert:
    datacenter: "Shadowman-DC"
    name: "{{ inventory_hostname }}"
    folder: "{{ path | regex_replace('^Datacenters/', '') }}"
    snapshot_name: "{{ name_of_snapshot }}"
    validate_certs: false
  delegate_to: localhost

- name: Turn on VM
  vmware.vmware.vm_powerstate:
    moid: "{{ vm_info.guests[0].moid }}"
    datacenter: "Shadowman-DC"
    state: powered-on
    validate_certs: false
  delegate_to: localhost
