---
- name: Create an incident in ServiceNow
  servicenow.itsm.incident:
    state: new
    description: "A firewall rule was created with the following entry: {{ event_logs | default(omit) }}"
    short_description: "A firewall rule was created and must be removed"
    caller: admin
    urgency: "high"
    impact: "high"
    other:
      u_operating_system: "{{ os | default(omit) }}"
      u_ip_address: "{{ ip_addr | default(omit) }}"
      u_vm_name: "{{ inventory_hostname | default(omit) }}"
      cmdb_ci: "{{ inventory_hostname | default(omit) }}"
  register: new_incident
  delegate_to: localhost

- name: Send notification message via Mattermost
  community.general.mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_api_key }}"
    attachments:
      - text: "! ALERT !"
        color: '#ff00dd'
        title: "Firewall Rule Created"
        fields:
          - title: Issue
            value: "A Firewall Rule was Created"
            short: true
          - title: Details
            value: "ServiceNow Incident: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=incident.do?sysparm_query=number={{ new_incident.record.number }} has been opened. Remediation in progress for a firewall rule created on {{ vm_name }}"
            short: true
          - title: Logs
            value: "{{ event_logs }}"
            short: true
  delegate_to: localhost

- name: Remove the firewall rule
  ansible.windows.win_shell: |
    Remove-NetFirewallRule -DisplayName "{{ ruletodelete }}"

- name: Close an incident in ServiceNow
  servicenow.itsm.incident:
    state: closed
    number: "{{ new_incident.record.number }}"
    close_code: Solved (Permanently)
    close_notes: "Firewall Rule was Removed"
  delegate_to: localhost

- name: Send notification message via Mattermost
  community.general.mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_api_key }}"
    attachments:
      - text: "! ALERT !"
        color: '#ff00dd'
        title: "Firewall Rule Issue Resolved"
        fields:
          - title: Issue
            value: "A Firewall Rule was Removed"
            short: true
          - title: Details
            value: "ServiceNow Incident: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=incident.do?sysparm_query=number={{ new_incident.record.number }} has been closed. A firewall rule has been removed from {{ vm_name }}"
            short: true
  delegate_to: localhost
